### ISSUE TITLE
UWP - Icons not displaying for contribution areas & contributor MVP status

### ISSUE THREAD

**Issue by jamesmcroft** [jamesmcroft/MS-MVP-Apps#19]
Appears to be an issue after build drop. No icons are being displayed for the MVP contribution areas.

**Comment by jamesmcroft** [comment]
Appears this also affects the MVP status on the contribution page also.

**Comment by LanceMcCarthy** [comment]
Possible missing ms-appx prefix?

**Comment by jamesmcroft** [comment]
Possibly. It may also be due to the fact that I only appear to have generated scale factor 400 images. Everything works locally when building through VS. Can take a look at this.

**Comment by jamesmcroft** [comment]
I believe this to be now fixed in the current master branch having tested the package output for the store. Will hold off on closing this off and publishing out for now.

**Comment by jamesmcroft** [comment]
This has been pushed out in the latest release and appears to be working fine.
