### ISSUE TITLE
Cannot update an existing activity

### ISSUE THREAD

**Issue by rfennell** [jamesmcroft/MS-MVP-Apps#24]
Maybe related to #23 i.e. MSA does not have correct rights.

Once logged in a try to edit an existing activity.

- Edited the reach, saved the item, reloaded it, the new value is not shown
- When editing the activity the visibility drop down is not populated

**Comment by jamesmcroft** [comment]
The issue does not appear to be related. 

This will need looking into.

**Comment by jamesmcroft** [comment]
This is partially fixed, will look into the issue with the visibility drop down save/load

**Comment by jamesmcroft** [comment]
Fixed the visibility issue. Will publish out a new release for testing.

**Comment by jamesmcroft** [comment]
You can now find the fix for this in the new release. If you're still experiencing an issue with this possibly linked to the Microsoft Account issue, we can re-open.
