### ISSUE TITLE
[UWP] Editing an existing contribution: visibility not remembered

### ISSUE THREAD

**Issue by bartlannoeye** [jamesmcroft/MS-MVP-Apps#25]
Opening one of my existing contributions, I verified the visibility was set in the app:

![image](https://cloud.githubusercontent.com/assets/5115577/23918431/35b8cb98-08f3-11e7-8182-462b52db21fc.png)

When going into edit mode, the visibility selection is lost:

![image](https://cloud.githubusercontent.com/assets/5115577/23918490/71e05a6e-08f3-11e7-8eae-b4306fb0a92d.png)

**Comment by bartlannoeye** [comment]
Aha, noticed it's already mentioned in #24 as second bullet. Feel free to close as dupe, or either split remembering this value from the actual update statement not being successful.

**Comment by jamesmcroft** [comment]
Will keep this separated for now as this issue is specific to the problem you're seeing. Thanks for spotting this

**Comment by jamesmcroft** [comment]
This should be fixed now. Will push out a new release.

**Comment by jamesmcroft** [comment]
Again, the fix for this can be found in the new release. Thanks for the finds
