### ISSUE TITLE
Can't add a contribution in the future

### ISSUE THREAD

**Issue by bartlannoeye** [jamesmcroft/MS-MVP-Apps#26]
This might feel counterintuitive at first, but I use this feature for 2 reasons:

* I typically register organized user groups events when they are put live (having everything available in EventBrite) and come back after the event to set the reach.
* This might change with the new renewal cycle, but in the past you had until e.g. Oct 5th to update your contributions, while all contributions until end of Oct were taken into account. So speaking engagements / organizing events / ... were items that you could typically add for that month (without reach ofc).

As a bonus:
Some people have their blog posts on a schedule, so those are items that can be scheduled (through the url protocol) as well.

It's all about keeping the friction/overhead as low as possible :)

**Comment by jamesmcroft** [comment]
This was a question that was asked to me by another MVP earlier and I had no idea you could schedule in the future for contributions. 

This is something that can be easily changed though.

**Comment by jamesmcroft** [comment]
Looking at the MVP website, there appears to be no restriction on how far in the future you can add contributions.

**Comment by jamesmcroft** [comment]
This will be fixed in the next test release 😄 Thanks for findings this

**Comment by jamesmcroft** [comment]
The fix for this can also be found in the new release 😄
