### ISSUE TITLE
[UWP] Calendar control unclear accross months

### ISSUE THREAD

**Issue by bartlannoeye** [jamesmcroft/MS-MVP-Apps#27]
Even though I'm adding a new contribution on today (March 14), at first sight I would think I'm adding a record for February.

![image](https://cloud.githubusercontent.com/assets/5115577/23919186/2f9563cc-08f6-11e7-9657-344c591c8381.png)

**Comment by jamesmcroft** [comment]
Not sure if making the changes in #26 might help with this issue. Do agree that this is unclear though.

**Comment by jamesmcroft** [comment]
Again, this will be fixed in the next test release 😄

**Comment by jamesmcroft** [comment]
You can now find this fix in the new release 😄
